accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('user/<username>', views.user_view, name="user"),
]

crisp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'), name='posts'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('', include('posts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('create/', views.post_create, name="create"),
    path('<slug:slug>', views.posts_detail, name="detail"),

]

accounts/models.py
from django.db import models

# Create your models here.

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Posts


# Create your models here.
class Comments(models.Model):

    author  = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    post    = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField(max_length=512)
    date    = models.DateTimeField(auto_now_add=True)
    score   = models.IntegerField(default=0)



    class Meta:
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.content

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Posts(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Posts.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Posts'

posts/forms.py
from django import forms
from . import models


class CreatePosts(forms.ModelForm):
    class Meta:
        model = models.Posts
        fields = ['title', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from posts.models import Posts


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('posts:list')


def user_view(request, username):
    if request.method == "GET":
        # check name mangling for author__username
        # initially used .get, but that is intended for a single
        # object only, so i had to change it to .filter =)
        user_posts = Posts.objects.filter(author__username=username)
        context = {
            'posts': user_posts.all(),
        }
        return render(request, 'accounts/user.html',context=context)

comments/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Posts
from . import forms
from comments import forms as comment_forms
from comments.models import Comments
# Create your views here.


def posts_list(request):
    posts = Posts.objects.all()
    context = {'posts': posts}
    return render(request, 'posts/posts_list.html', context)


def posts_detail(request, slug):
    post = Posts.objects.get(slug=slug)
    context = {
        'post': post,
        'comments': post.comments_set.all(),
    }
    if request.method == 'POST':
        Comments.objects.create(author=request.user, post=post, content=request.POST.get('content', ''))
        return redirect('posts:detail', slug)
    return render(request, 'posts/posts_detail.html', context)


@login_required(login_url="/accounts/login/")
def post_create(request):
    if request.method == 'POST':
        form = forms.CreatePosts(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePosts()
    return render(request, 'posts/post_create.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

accounts/templates/accounts/user.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Profile Information</h1>
    <div class="Memes">
        {% for i in posts %}
            <div class="Meme">
                <div class="title"><a href="{% url 'posts:detail' i.slug %}">{{ i.title }}</a></div>
                <img src="{{ i.thumb.url }}">
                <div class="date">added on {{i.date}}</div>
                <div class="score">Current score {{ i.score }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base_layout.html' %}
{% block content %}
    <div class="create-post">
        <h2>Blaze the community with a deadly meme!</h2>
        <form class="site-form" action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <!-- <script src="/static/slugify.js"></script> -->
{% endblock %}

posts/templates/posts/posts_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="post-container">
        <div class="post-detail">
            <div class="post-detail-title">{{ post.title }}</div>
            <div class="post-detail-image"><img src="{{ post.thumb.url }}"></div>
            <div class="post-detail-author"> Added by <a href="{% url 'accounts:user' post.author.username %}"> {{ post.author.username }} </a></div>
        </div>
        {% if user.is_authenticated %}
        <div class="add-comment">
                 <form class="comment-form" action="{% url 'posts:detail' post.slug %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                     <input type="text" name="content" required>
                     <input type="submit" value="Have a say!">
                </form>
        </div>
        {% endif %}
        <div class="comments-title">Comments</div>
        <div class="post-comments">
            {% for comment in comments %}
                <div class="single-comment">
                    <div class="comment-author">{{ comment.author.username }} said:</div>
                    <div class="comment-content">{{ comment.content }}</div>
                    <div class="comment-date">{{ comment.date | timesince }} ago</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Memes</h1>
    <div class="Memes">
        {% for i in posts %}
            <div class="Meme">
                <div class="title"><a href="{% url 'posts:detail' i.slug %}">{{ i.title }}</a></div>
                <img src="{{ i.thumb.url }}">
                <div class="author">added by <a href="{% url 'accounts:user' i.author %}">{{ i.author }}</a></div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Crisp</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
        <header class="wrapper">
        <h1><a href="{% url 'posts:list' %}"><img style="height: 200px; width: auto; margin-top: -50px" src="{% static 'logo.png' %}" alt="crisp" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <a href="{% url "accounts:user" user.username %}">{{ user.username}}</a> | <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'posts:create' %}" class="highlight">New Meme</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>